### ISSUE TITLE
Use native ES6 Promises (move away from bluebird) for the javascript driver

### ISSUE THREAD

**Issue by benseitz** [rethinkdb/rethinkdb-legacy#6459]
Since ES6 Promises are available for all important node versions ([http://node.green/#ES2015-built-ins-Promise](http://node.green/#ES2015-built-ins-Promise)) I think it would be possible to move away from bluebird  (which is currently the only dependency for the javascript driver!)

Some implementation where you can easily plug in your favorite promise library would be nice too ([like something mongoose did](http://mongoosejs.com/docs/promises.html))

**Comment by marshall007** [comment]
We'll accept a PR implementing this behavior if anyone wants to take a stab at it! I like the idea of making the Promise implementation pluggable as @benseitz described.

**Comment by benseitz** [comment]
I would love to give it a shot. 
How would you suggest implementing the pluggable Promises?

Something like `r.Promise = require('bluebird')`?

**Comment by marshall007** [comment]
@benseitz yea, but I think it would be better to expose a method for setting the promise implementation than assigning to a property:

```js
const Promise = require('bluebird');
r.setPromise(Promise);
```

That way we can detect if/when a user attempts to call `r.setPromise(...)` multiple times (or after a connection has already been established) and throw an error in that case. You don't want people to modify the promise implementation after initialization (either by accident or on purpose) as it could lead to weird runtime side-effects.

Also note, we won't be able to remove `bluebird` entirely as a dependency. The default promise implementation is still going to have to be `bluebird`, otherwise it's a huge breaking change. I think the best we could do for now is make it a `peerDependency`.
